### ISSUE TITLE
Size of lightbulb.png is too big 128x128px.

### ISSUE THREAD

**Issue by segitwo** [emacs-lsp/lsp-ui#570]

**Comment by ericdallo** [comment]
Yeah, the ideal sould be to replace it with a .svg

**Comment by sebastiencs** [comment]
What is the issue with that size ?
The image is resized (to make it smaller) and visually it should fits in the line.

By using a smaller size, the image would have to be resized too, but by making it bigger and it would appear pixelated.

> Yeah, the ideal sould be to replace it with a .svg, not sure emacs supports svg though

Emacs does support svg images, but it requires a compile time flag, and not all linux distribution package Emacs with that flag

**Comment by ShadyAlfred** [comment]
![image](https://user-images.githubusercontent.com/3685582/107153667-73d07c80-6977-11eb-9bcc-d270b656b9c3.png)

When I hover over lines with errors or warnings, the height of the lines increases, then when I move away it decreases. It is kinda annoying seeing the lines glitching like this.

**Comment by hammerandtongs** [comment]
This is pretty painful as is.

The lightbulb is about 5 lines tall and it causes the text to jump around it as i scroll along.

Is there a simple way to disable the lightbulb for now?

**Comment by sebastiencs** [comment]
@ShadyAlfred @hammerandtongs Can you please post the value of those 3 variables:
`system-configuration`, `system-configuration-options` and `system-configuration-features`

You can disable it with `(setq lsp-ui-sideline-actions-icon nil)`

**Comment by ShadyAlfred** [comment]
`system-configuration`
![image](https://user-images.githubusercontent.com/3685582/107223521-f2342980-6a1e-11eb-81b5-9e94b9cd53aa.png)

`system-configuration-options`
![image](https://user-images.githubusercontent.com/3685582/107223584-08da8080-6a1f-11eb-8869-d2747df6fb28.png)

`system-configuration-features`
![image](https://user-images.githubusercontent.com/3685582/107223656-20b20480-6a1f-11eb-8796-e311f1a427d3.png)

**Comment by hammerandtongs** [comment]
"x86_64-pc-linux-gnu"

`"--build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --build x86_64-linux-gnu --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib --localstatedir=/var/lib --infodir=/usr/share/info --mandir=/usr/share/man --enable-libsystemd --with-pop=yes --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/26.3/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/26.3/site-lisp:/usr/share/emacs/site-lisp --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs-mEZBk7/emacs-26.3+1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'"`

`"XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2"`

**Comment by padraic00** [comment]
Any updates on this?

**Comment by yyoncho** [comment]
@jcs090218 is this fixed with https://github.com/emacs-lsp/lsp-ui/commit/63533f120ade4af71d0744ae7bd208e1b9420a1f ?

**Comment by jcs090218** [comment]
> @jcs090218 is this fixed with 63533f1 ?

@yyoncho I did fix the glitch.

---

But since there is no description from the author so I don't know if I should close this issue.

@padraic00 Can you update to the latest version and see does the commit 63533f120ade4af71d0744ae7bd208e1b9420a1f suit your needs? Thanks!

**Comment by padraic00** [comment]
> @padraic00 Can you update to the latest version and see does the commit [63533f1](https://github.com/emacs-lsp/lsp-ui/commit/63533f120ade4af71d0744ae7bd208e1b9420a1f) suit your needs? Thanks!

currently on [78e0a41](https://github.com/emacs-lsp/lsp-ui/commit/78e0a41c9b6b0a166c6c86d2541f310883d15b68). Still unfixed.

**Comment by ericdallo** [comment]
Alright, @yyoncho @jcs090218 since the issue is not solved, can we disable that icon by default and re-enable it when fixed?
We already have #573 and https://github.com/emacs-lsp/lsp-mode/issues/2628, so it seems to affect multiple users

**Comment by jcs090218** [comment]
Let's move this issue to #573 since I think it has a better bug report. :)

Close this issue now.
