### ISSUE TITLE
is it a feature or bug ?

### ISSUE THREAD

**Issue by samrayleung** [emacs-lsp/lsp-ui#90]
I am not sure it is a feature of `lsp-ui` or a bug, but from my point of view, it seems a bug. After I call `lsp-ui-peek-find-reference`, all parentheses get highlighted for no reason, here is the screenshot:

![screenshot_2018-03-03_16-52-12](https://user-images.githubusercontent.com/14180681/36932453-1f625896-1f04-11e8-9043-2a0668149bc6.png)

![screenshot_2018-03-03_16-52-31](https://user-images.githubusercontent.com/14180681/36932458-289a2236-1f04-11e8-8f3e-504b11724317.png)

Information about my Emacs environment:
+ OS: Arch Linux
+ lsp-ui version: lsp-ui-20180224.2300
+ lsp-mode version: lsp-mode-20180224.246/
+ Emacs version: 25.3
+ theme: it happens with zenburn and sanityinc-tomorrow-eighties theme

Hope you guys could help me solve this problem :)

**Comment by sebastiencs** [comment]
hmm that's a bug, might be related to #93

**Comment by sebastiencs** [comment]
@samrayleung  Can you test https://github.com/emacs-lsp/lsp-ui/commit/d2eb4ec8a70742a5c589c140c414224795b5b4b7 ? It should fix the bug

**Comment by samrayleung** [comment]
Yes, it fix the bug. By the way, as for this [issue](https://github.com/emacs-lsp/lsp-ui/issues/87), perhaps it isn't related to Chinese words, since I have updated Emacs to 26.0 and open a new project with no Chinese word, I still have this issue. 

![screenshot_1](https://user-images.githubusercontent.com/14180681/37400441-e813ac90-27bf-11e8-9a68-6c99b50befcb.png)

**Comment by sebastiencs** [comment]
@samrayleung Do you have any particular settings with your margins and/or fringes ?
This is related to https://github.com/emacs-lsp/lsp-ui/issues/31

**Comment by samrayleung** [comment]
This is all my setting related to fringes, is it related to this issue ?
```
(fringe-mode '(10 . 0))
(defun samray/tone-down-fringes ()
  "Set the fringe colors to whatever is the background color."
  (set-face-attribute 'fringe nil
                      :foreground (face-foreground 'default)
                      :background (face-background 'default)))
(add-hook 'after-load-theme-hook 'samray/tone-down-fringes)
```

**Comment by sebastiencs** [comment]
Yes, I can reproduce. I'm working on it

**Comment by sebastiencs** [comment]
@samrayleung https://github.com/emacs-lsp/lsp-ui/commit/88827e848440eaa3348243e8fa11926cce24aa0d and https://github.com/emacs-lsp/lsp-ui/commit/6ba9d3fe2d9c0f239ebd8a124e10bc038c76fdb3 should address that. Can you test `lsp-ui-sideline` and `lsp-ui-peek` ?

**Comment by samrayleung** [comment]
It works. Thanks so much for your hard work :)
